### ISSUE TITLE
Resuming incremental search requires two presses of C-s

### ISSUE THREAD

**Issue by m27315** [tuttieee/vscode-emacs-mcx#108]
## Steps to Reproduce:
1. Search for some word using C-s.
2. Move to blank line or some space without a word under the cursor, so incremental search history is preserved (see #107).
3. Resume incremental search (C-s).
4. Note that previous search is recalled and matches are hightlighted.  However, searching has not begun.
5. Press C-s **again** to jump to the **next** match.  

## Expected Behavior
Resuming incremental search would have immediately resumed the search and jumped to the next match from current cursor location.

## Versions
```
Awesome Emacs Keymap: 0.11.2
VSCode Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.27-gentoo-r1
```

**Comment by joeshaw** [comment]
I wonder if binding to "Find Next" in all cases (ie, not just when `findWidgetVisible`) is the right way to handle this.  Unfortunately, "Find Next" doesn't highlight the find widget, so you couldn't enter new text in that case.  I'm not sure if that can be worked around, though.

**Comment by joeshaw** [comment]
A hack I threw together for this which seems to work is:

```
export class Find extends EmacsCommand {
    public readonly id = "find";
    
    public execute(textEditor: TextEditor, isInMarkMode: boolean, prefixArgument: number | undefined) {
        return vscode.commands.executeCommand("actions.find").then(() => vscode.commands.executeCommand("editor.action.nextMatchFindAction"));
    }
}
```

Probably an abuse of overriding `EmacsCommand` for this, but executing the `actions.find` command first and then the `editor.action.nextMatchFindAction` gets the job done in an emacs-like fashion (other than not extending the mark selection as matches happen 😕)

**Comment by m27315** [comment]
@joeshaw, is there a way I can try the above "hack"?

**Comment by tuttieee** [comment]
@joeshaw Thank you for the suggestion. Can you send a patch?

**Comment by joeshaw** [comment]
I submitted a PR for it, #209.
