### ISSUE TITLE
Some of keybindings stop to work after some time

### ISSUE THREAD

**Issue by tgrk** [tuttieee/vscode-emacs-mcx#111]
First of all, thank you for the best Emacs keybinding for VSCode!

I am a Linux (Ubuntu) user and I am facing "random" issues when a certain group of key shortcuts stops working (after some time). Most noticeable are `alt+backspace`, `alt+k` or `alt+d`... I expect to be some issue with another extension (and Linux or Window Manager). It is a bit painfull so any advice (even on how to effectively debug this issue as I am happy to provide patch) is much appreciated.

Keep up great (well awesome :smiley: ) work

**Comment by tuttieee** [comment]
Sorry for my late reply and thank you for reporting!

1. When this problem happens, does the extension crash with an error dialog like "Extension host terminated unexpectedly"? If so, this is a problem described in #98 . It's now under inspection. sorry.
2. If not, can you please check the output of the developer tools' console when the problem happens and paste it here? You can open the developer tools via the command palette with "Toggle Developer Tools" command.

**Comment by tuttieee** [comment]
Please report it again if it still occurs.
