### ISSUE TITLE
moveBeginningOfLine moves to indent, not first column of line

### ISSUE THREAD

**Issue by joeshaw** [tuttieee/vscode-emacs-mcx#113]
If you have some indented code, like so:

```go
package main

func main() {
	fmt.Println("hello world")
}
```

Place your cursor on the `fmt.Println` line.  If you hit C-a, you jump to the `f` of `fmt.Println`.  I would expect this to go to the first column of the line, not to the indentation.  This is what Emacs does out of the box, and what the VSCode command `cursorLineStart` does.

If the `f` is highlighted, pressing C-a does jump to the start of the line, though.

**Comment by tuttieee** [comment]
Hello,
Yes, this behavior is different from the original emacs as you said.
I think, however, there might be some discussions which behavior should be implemented in this extension. I don't know which behavior the users of this extension prefer.
I mean, which should we aim to, "emacs-flavored vscode" or "strictly emacs-like vscode".

So, I will implement "both" based on your PR and make switchable them by the config.
