### ISSUE TITLE
Make windows space evenly

### ISSUE THREAD

**Issue by mateusfccp** [tuttieee/vscode-emacs-mcx#141]
On emacs, if you press `C-x +` the windows are evenly spaced . I use it a lot on emacs, but in VSCode it would be even better, as my Windows are always unevenly spaced.

Would it be possible to implement this keybinding?

**Comment by tuttieee** [comment]
Hello, I think VScode makes split windows the same sizes by default.
Here is an example screenshot after I typed `C-x 3` 2 times to get 3 split windows.
<img width="1053" alt="スクリーンショット 2019-09-29 19 12 51" src="https://user-images.githubusercontent.com/3135397/65830730-2822b300-e2ed-11e9-88c5-2cfbf07c6627.png">
As it shows, the emacs behavior of (`C-x +`) is already realized VScode by default.

Please let me know if there is anything I miss.
Thanks.
