### ISSUE TITLE
Expanding selection fails in some directions (mark mode)

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [tuttieee/vscode-emacs-mcx#142]
The following sequence works well (selection is extended properly)

1. `emacs-mcx.setMarkCommand` `Ctrl+Space`
2. `emacs-mcx.previousLine` `Ctrl+P`

but this one doesn't:

1. `emacs-mcx.setMarkCommand` via `Ctrl+Space`
2. `emacs-mcx.nextLine`  via `Ctrl+N`

In fact, `nextLine` just doesn't work well for me. I'm using the latest version to my knowledge. 

I'm in the latest version for the extension. Info for VSCode and OS below:

```
Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:35:11.314Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0
```

**Comment by tuttieee** [comment]
hmm, I don't find such a behavior with the latest version of the extension, VScode, and MacOS.

1. Can you please check if `emacs-mcx.nextLine` command is actually assigned to `ctrl+n` from the keyboard shortcut config page.
For example, in my environment, it is shown like this: <img width="527" alt="Keyboard_Shortcuts" src="https://user-images.githubusercontent.com/3135397/67146551-21bda080-f2c7-11e9-9fb9-32b1878e3300.png">
2. If the command is properly assigned, please configure this extension to output debug logs by following #102 and paste all the output logs here.

**Comment by amelio-vazquez-reina** [comment]
Thanks that was it! 👍
