### ISSUE TITLE
Paragraph movement 

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [tuttieee/vscode-emacs-mcx#143]
Does this extension already support [paragraph movement](https://www.gnu.org/software/emacs/manual/html_node/emacs/Paragraphs.html)? 

I started using the VSCode extension [Space Block Jumper](https://marketplace.visualstudio.com/items?itemName=jmfirth.vsc-space-block-jumper) (e.g. its `Move Up` and `Move Down` commands) but mark mode from `vscode-emacs-mcx` doesn't work with them.

**Comment by tuttieee** [comment]
Currently it's not supported.
Thank you for telling your needs and I will add it to the roadmap.

For now, this plugin exposes `emacs-mcx.inMarkMode` flag for `when` context (see: https://github.com/tuttieee/vscode-emacs-mcx#when-clause-context , https://github.com/tuttieee/vscode-emacs-mcx/issues/56#issuecomment-457120445 )
and [this discussion](https://github.com/tuttieee/vscode-emacs-mcx/issues/114) may help you.

**Comment by amelio-vazquez-reina** [comment]
Excellent - Thanks @tuttieee! I finally got to follow through on this and the snippet here: https://github.com/tuttieee/vscode-emacs-mcx/issues/56#issuecomment-457120445 did exactly what I was looking for.
