### ISSUE TITLE
Can't use in the jupyter notebook file maybe.

### ISSUE THREAD

**Issue by A11en0** [tuttieee/vscode-emacs-mcx#145]
Say as title. It can't use in the .ipynb files.

**Comment by tuttieee** [comment]
It seems the Jupyter Plugin uses WebView, and its cursor movements and other interactions are controlled by different way from the VSCode's native editor.
It cannot be touched by this extension.

Hint:
The current version of Jupyter plugin does not expose any commands to control cursors or other interactions, like "cursorLeft" command in the native editor which moves the cursor.
I suggest you make a suggestion or pull-request to the Jupyter plugin's repository to expose such APIs.

**Comment by sickerin** [comment]
@A11en0  long story short, after digging around on the vscode and vscode-python repos. It seems it'll be a pretty big task, and would require collaboration from both repos. PMs would need to approve things and seems like things need to rewritten or implementations changed. So, it's unlikely to happen in the meantime.

**Comment by andyliumathematics** [comment]
Using .py  and split the code block with "# %%"  can work with vim.
