### ISSUE TITLE
Bindings that start with C-k broken and no "undo undo"

### ISSUE THREAD

**Issue by bmolinh** [tuttieee/vscode-emacs-mcx#150]
Hey, I don't know if there's a way of integrating transactional undoing like in emacs described here https://stackoverflow.com/a/3527182 but most important, theres like 20 or so commands in vscode that are bind starting with "C-k" which will make you delete a line and not be able to complete the other keybind, I propose they should be changed to start with eXtended command "C-x".

**Comment by tuttieee** [comment]
This extension is not capable of undoing undos.
It just binds keys to VSCode's native undo command.

> I propose they should be changed to start with eXtended command "C-x".

Thank you for the suggestion, but `C-k` command is heavily used by Emacs users and I think it shouldn't be changed as long as we expect this extension to behave like Emacs.
Please disable that specific keybinding by your user-level keybindings.json if you have trouble with  it or assign the conflicted commands to other keybindings. It will be great if you share info about or send a patch including such key assignments.

**Comment by zeeshansayyed** [comment]
Hi @tuttieee I might be wrong, but I think @bmolinh meant that can we change all the commands which start with C-k in VScode to start with C-x instead. That way it will be easier to remember them.
