### ISSUE TITLE
Paste into findWidget

### ISSUE THREAD

**Issue by r-giskard-reventlov** [tuttieee/vscode-emacs-mcx#159]
When yank is used in findWidget the contents of the clipboard are not pasted.

**Comment by tuttieee** [comment]
We cannot customize keybindings in the find widget, so this extension does not work either.
It's VSCode's restriction.
Please see https://github.com/tuttieee/vscode-emacs-mcx/issues/137#issuecomment-518487336

**Comment by whitphx** [comment]
This is no longer true; I found a command to paste a text from clipboard to the find widget and assigned it to `ctrl+y`, so that `C-y` actually works on the find widget.
I will be available from the next release, 0.78.0.

**Comment by whitphx** [comment]
btw

> disabling the C-v customization and allowing default behavior (paste) when search is in focus?

This was introduced since 0.73.0. Sorry for a long delay.
