### ISSUE TITLE
Feature request: kill-whole-line option

### ISSUE THREAD

**Issue by PicoSushi** [tuttieee/vscode-emacs-mcx#168]
Hello, I'm so appreciated this plugin!

Original Emacs has useful option `kill-whole-line`, and emacs-mcx will become more excellent if this option is supported.

> If the variable kill-whole-line is non-nil, C-k at the very beginning of a line kills the entire line including the following newline. This variable is normally nil.
> https://www.gnu.org/software/emacs/manual/html_node/emacs/Killing-by-Lines.html#Killing-by-Lines

**Comment by tuttieee** [comment]
Thank you for the suggestion, I will consider it.
