### ISSUE TITLE
"values not accepted" in keybindings.json

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [tuttieee/vscode-emacs-mcx#196]
Issue Type: <b>Bug</b>

VSCode complains that none of my `emacs-mcx` shortcuts from this extension are accepted, even though they work fine. I'm using insiders, the latest version from today (March 6th, '20) although I have been experiencing this problem for days / weeks now.

Extension version: 0.14.1
VS Code version: Code - Insiders 1.43.0-insider (b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0, 2020-03-04T23:55:34.718Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|64.00GB (23.67GB free)|
|Process Argv|-psn_0_7862143|
|Screen Reader|no|
|VM|0%|
</details>

Example here:
<img width="507" alt="Screen Shot 2020-03-06 at 10 46 22 AM" src="https://user-images.githubusercontent.com/1993919/76098977-686f1700-5f98-11ea-99d5-10b292864654.png">

I have 17 keyboard shortcuts for this extension, all of them reporting the same problem.

<img width="1128" alt="Screen Shot 2020-03-06 at 10 51 37 AM" src="https://user-images.githubusercontent.com/1993919/76099051-863c7c00-5f98-11ea-9baa-24b4cf50284b.png">

**Comment by tuttieee** [comment]
@amelio-vazquez-reina 
Thank you for the report.
Is it a VSCode's bug?
Or does it seem to be related to the specific extension?

**Comment by amelio-vazquez-reina** [comment]
I have always only seen this problem with this specific extension. But to be honest, I'm using Insiders, so every day I get a new update, and at this very moment I don't have any problems reported.

**Comment by tuttieee** [comment]
Thank you, then I close this issue.
Please reopen it if there will be this problem again in the next stable release.

**Comment by amelio-vazquez-reina** [comment]
This problem came back (see screenshot below). 

![Uploading Screen Shot 2020-04-10 at 6.43.21 PM.png…]()

**Comment by amelio-vazquez-reina** [comment]
I can't re-open this issue myself @tuttieee How would you suggest we proceed?

**Comment by tuttieee** [comment]
Oh, you cannot reopen it.
I didn't know that it's impossible...
Then, please mention me in this thread like above or create a new issue if necessary.

---

Regarding the issue itself, I cannot support the insider version of VSCode, sorry.

**Comment by amelio-vazquez-reina** [comment]
Thanks @tuttieee I appreciate it. I'll try to confirm whether or not I experience this problem in the latest stable version of VSCode as well.
