### ISSUE TITLE
Feature request: exchange-point-and-mark

### ISSUE THREAD

**Issue by mtstlgh** [tuttieee/vscode-emacs-mcx#253]
Thank you for creating this lovely extension! I'm very happy with it.

Could you support "exchange-point-and-mark" used to move to a yanked or marked position?
<https://www.gnu.org/software/emacs/manual/html_node/emacs/Setting-Mark.html>
I think the extension will be more useful if `C-x C-x` is supported.

This is a feature rarely found in other extensions. As far as I know, it can only be used in vscode-emacs-flavor: <https://github.com/tommas1988/vscode-emacs-flavor>.

Or is there some kind of alternative way?

**Comment by tuttieee** [comment]
Thank you for the suggestion. I will consider it.

**Comment by mtstlgh** [comment]
Thank you for dealing with this issue!
