### ISSUE TITLE
C-y does not yank what I killed after repeated C-k

### ISSUE THREAD

**Issue by ganaware** [tuttieee/vscode-emacs-mcx#26]
連続した C-k の動作が、Emacs の動作とは異なるようです。
C-k を連続して複数回行った後に C-y を押すと、

- Emacs では、最初の C-k から kill したものが全て繋がったものがペーストされる
- Awesome Emacs Keymap では最後の C-k で kill したものだけがペーストされる

となっていました。

https://www.gnu.org/software/emacs/manual/html_node/emacs/Killing-by-Lines.html

このあたりの動作は  SebastianZaha のものでは期待通りに動作しています。

**Comment by tuttieee** [comment]
ありがとうございます、killの動作について理解が甘かったです。
こちらですね: https://www.gnu.org/software/emacs/manual/html_node/emacs/Appending-Kills.html

修正します。

**Comment by ganaware** [comment]
v0.1.2 で、連続した C-k の動作が Emacs と同じようになっているのを確認しました。
対応ありがとうございました。
