### ISSUE TITLE
Please support C-M-f, C-M-b

### ISSUE THREAD

**Issue by ganaware** [tuttieee/vscode-emacs-mcx#27]
Please support C-M-f, C-M-b:

https://www.gnu.org/software/emacs/manual/html_node/emacs/Expressions.html

- C-M-f
    - Move forward over a balanced expression (forward-sexp). 
- C-M-b
    - Move backward over a balanced expression (backward-sexp). 

この2つの動作は Emacs の動作を完全に真似しようとするとかなり大変なのですが、いくつかの拡張では導入されています。

- Emacs Keybindings with S-exp
    - https://marketplace.visualstudio.com/items?itemName=haruhi-s.vscode-emacs
- Emacs Keymap Improved
    - https://marketplace.visualstudio.com/items?itemName=rkwan94.vscode-emacs-improved

個人的には、これらの動作をS式中での移動目的で使用したことはなく、対応する括弧へジャンプする機能としてのみ使用しています。ですので、そのような動作をしてくれるだけでもありがたいです。

**Comment by ganaware** [comment]
対応ありがとうございます。v0.1.2 で対応する括弧にジャンプできることを確認いたしました。

ただ、少し気になるのが #23 とのキーバインディングのコンフリクトです。
haruhi-s さんの sexp 拡張では、M-u に sexp.barf を割り当てています。
これを無効にしたうえで、 #23 の M-u を有効にする、
といった実装はうまくできるものなのでしょうか?
(拡張の読み込み順が必ず sexp ⇒ awsome Emacs Keymap となってくれるなら良いのですが)

**Comment by tuttieee** [comment]
ご指摘ありがとうございます。
調べきれていないのですが、"when"を指定するとpriorityが上がり、overrideできるようです（ https://github.com/Microsoft/vscode/issues/10004 ）
sexpのkeybinding定義では"when"がないのに対し、本Extentionではwhenを指定しているので、こちらのkeybindingが優先されるのではないかと思います。

もしこの通りの挙動にならない事象に遭遇したらIssueを立てていただけると嬉しいです。
よろしくお願いします。

**Comment by ganaware** [comment]
v0.1.3 で確認いたしましたが、本Extensionのほうが優先されて動作していました。ありがとうございました。
