### ISSUE TITLE
C-o does not work

### ISSUE THREAD

**Issue by ganaware** [tuttieee/vscode-emacs-mcx#28]
README.md:

|Command | Desc |
|--------|------|
| `C-o` | Open line (This keybinding is provided by native VSCode, but not this extension) |

What does it mean? When I enter C-o, VSCode always show the Open File dialogue. How to use open-line?

https://www.gnu.org/software/emacs/manual/html_node/emacs/Blank-Lines.html

**Comment by tuttieee** [comment]
Oh, sorry, I will define the keybinding explicitly in `package.json` and fix it.
This is probably because you are using not macOS version, in whose keybinding `ctrl+o` is defined as `lineBreakInsert`, but not in other platforms.

**Comment by ganaware** [comment]
Yes, I'm using Windows version on Windows7, Windows10.

Now,  C-o works fine with new version v0.1.1.
Thank you.
