### ISSUE TITLE
Ctrl-[Space] Ctrl-W doesn't work on same line

### ISSUE THREAD

**Issue by epchristi** [tuttieee/vscode-emacs-mcx#288]
<Mark> <Kill buffer> doesn't seem to work on the same line. If the buffer spans more than one line, it works fine.

To reproduce:
Ctrl-[Space] => Use Ctrl-[Right Arrow] => Ctrl-W
(Turns out this will work if M-f is used to forward through words, so you may choose not to fix this, but it would be nice.) 

Love this extension!

**Comment by tuttieee** [comment]
Hello,

`Ctrl-[Right Arrow]` is not assigned to any command in this extension by default and it's natural it does not work in that scene. I think `Ctrl-[Right Arrow]` does not make any cursor movements if you use this extension without any other plugins and/or your original keybindings.

If it moves the cursor in your VSCode, I think it's done by another extension or your user-level keybindings and it does not cooperate with this extension's mark-mode (`C-Space`).
This extension manages its mark-mode state inside it and exposes special commands to move the cursor such as `emacs-mcx.forwardChar` compatible with the mark-mode. If you want to use `Ctrl-[Right Arrow]` keybinding with this extension's mark-mode, you have to assign it to the commands exposed by this extension.
For example, `right arrow` and `C-f` are assigned to `emacs-mcx.forwardChar` command by default, that moves the cursor forward cooperating with the mark-mode.
