### ISSUE TITLE
kill word not working as expected in json files

### ISSUE THREAD

**Issue by schmeic** [tuttieee/vscode-emacs-mcx#321]
If I have something like this in a json file:
```"test": "here are some words"```

and I have the cursor right before the "h", M-d will delete everything up to and including the " at the end of the line. However, M-f just moves to the end of the word "here" as expected.
Not sure if this has anything to do with this extension, but this is my only keybinding for M-d.
M-d works as expected in other file types.

**Comment by tuttieee** [comment]
Thank you. I will try to fix it.

**Comment by tuttieee** [comment]
This will be in the next release, 0.20.4

**Comment by tuttieee** [comment]
Released.
