### ISSUE TITLE
What is the recommended way of Redo in the extension?

### ISSUE THREAD

**Issue by zeeshansayyed** [tuttieee/vscode-emacs-mcx#331]
In Emacs, we can undo the undo by first making a non editing change and then pressing undo again. That doesn't seem to always work in the extension. Is there a recommended way of doing things in this extension?

Thanks for the awesome extension btw.

**Comment by carllerche** [comment]
In my editor, it is bound to `ctrl + shift + z`

**Comment by tuttieee** [comment]
@zeeshansayyed 
This extension does not have the original undo behavior that can undo the previous undos.
Please see [this comment](https://github.com/tuttieee/vscode-emacs-mcx/issues/150#issuecomment-599577520) too.

**Comment by zeeshansayyed** [comment]
Thanks. Should I close this issue?
