### ISSUE TITLE
Please support kill-sexp

### ISSUE THREAD

**Issue by kshartman** [tuttieee/vscode-emacs-mcx#392]
Set Mark
(Prefix Argument) Forward Sexp
Kill Region

This may be a dupe (subset) of support full paredit.js capabilities.

Great extension.  Thanks!

**Comment by kshartman** [comment]
using the multi-command extension I can actually do this as follows:

// settings.json:
 {
            // [Optional] Kill Next Sexp
            "command": "multicmd.emacs-mcx.killSexp",
            "sequence": [
                "emacs-mcx.setMarkCommand",
                "emacs-mcx.paredit.forwardSexp",
                "emacs-mcx.killRegion"
            ]
}

// keybindings.json
{
        "key": "ctrl+alt+k",
        "command": "multicmd.emacs-mcx.killSexp",
        "when": "editorTextFocus && !editorReadonly"
}

**Comment by tuttieee** [comment]
Thank you for the suggestion.
I will try it.
