### ISSUE TITLE
Consider publishing to OpenVSX marketplace

### ISSUE THREAD

**Issue by sunng87** [tuttieee/vscode-emacs-mcx#400]
I'm using vscodium which uses openvsx for extension marketplace. Currently there is no emacs keymap extension available on that marketplace. I would recommend you to release this emacs extension there. Thanks!

**Comment by tuttieee** [comment]
I published the extension on OpenVSX, though the namespace is and the extension is marked as unverified yet.
I'm claiming the ownership of the namespace now and it will be marked as verified after it is accepted.
https://open-vsx.org/extension/tuttieee/emacs-mcx

**Comment by sunng87** [comment]
@tuttieee thank you very much!
