### ISSUE TITLE
characters chaos when inputting chinese characters after updated newest vscode

### ISSUE THREAD

**Issue by shoutrain** [tuttieee/vscode-emacs-mcx#425]
after I updated the newest vscode, i found following issue:

when I want to instert chinese characters ("中文") in following sentence (after ":"):
```javascript
console.log('input chinese:');
```
I got the following result:
```javascript
console.log('input chinesez中文');
```
The correct result should be:
```javascript
console.log('input chinese:中文');
```

My vscode version info:
```txt
Version: 1.49.0 (system setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by tuttieee** [comment]
It looks like the issue #115 .
Please try to set `emacs-mcx.disableOverridingTypeCommand` config to `true` (See: https://github.com/tuttieee/vscode-emacs-mcx#emacs-mcxdisableoverridingtypecommand ).

However it also may be a different problem since you said this issue appeared after you updated VSCode to 1.49.0.
Can you tell me the following information if possible?
* The previous version of VSCode
* The current and previous version of Awesome Emacs Keymap

Also, please let me know the keystroke to type the Chinese string "中文" with IME.

**Comment by shoutrain** [comment]
@tuttieee 

1. setting emacs-mcx.disableOverridingTypeCommand config to true  makes no sense to this issue.

2. sorry, i am not sure previous version of vscode and Awesome Emacs Keymap， i update these two every time when I get notice they can be updated (from left bottom manageicon in vscode).

3. yes, i found more dedails about this issues, hope helps:

| original string |  input chinese characters | corresponding keystoke | actual result string | expected destine string |
| --- | --- | --- |--- | --- |
| chinese | 中文 | zhongwen | chinesz中文 | chinese世界 |
| hello | 世界 | shijie | hells世界 | hello世界 |
| 中文 | 你好 | nihao| 中n你好 | 中文你好 |

looks the first keystoke character replaces the previous last character.

**Comment by tuttieee** [comment]
Another possible workaround is to use an older version of VSCode and this extension, as this issue raises when you upgraded VSCode and the extension.
You can download older versions of VSCode here: https://code.visualstudio.com/updates/v1_48
and install older versions of this extension from the menu of extension browser (See "Install Another Version" is there below).
<img width="546" alt="スクリーンショット 2020-09-18 23 49 27" src="https://user-images.githubusercontent.com/3135397/93611785-b1089200-fa09-11ea-9d7b-90495e843ddd.png">

**Comment by shoutrain** [comment]
> Thank you.
> It seems similar to #115 according to the details you provided, but I don't know why it is still there...
> One thing, did you reload VSCode after you changed `emacs-mcx.disableOverridingTypeCommand` config? If not, please try it and check whether the issue still occurs. I forget to tell it, sorry.
> 
> If the problem will still be not solved, can you tell me the IME you are using? I will try to reproduce the bug.

@tuttieee HI, yeah! you are right, I should have restarted VSCode after setting `emacs-mcx.disableOverridingTypeCommand` with true.  Now it works fine.  Thank you very much!  also this emacs-keys plugin is the best one on vscode!!!

PS: my chinese IME is provided by windows 10 system, its name is Microsoft Pinyin.
