### ISSUE TITLE
Closing vscode

### ISSUE THREAD

**Issue by n1rdeks** [tuttieee/vscode-emacs-mcx#427]
after closing VSCode, in process list still sit your extension:

```
ps ax | grep extension
 /home/n1rdeks/.vscode/extensions/tuttieee.emacs-mcx-0.20.4/dist/fallbacks/linux/xsel --clipboard --input
```

Please, write command for stop this process after closing VSCode

**Comment by tuttieee** [comment]
From v0.21.0, `xsel` is no longer used
