### ISSUE TITLE
Add support for M-m

### ISSUE THREAD

**Issue by cheeze2000** [tuttieee/vscode-emacs-mcx#439]
`M-m (back-to-indentation)`
https://www.gnu.org/software/emacs/manual/html_node/emacs/Indentation-Commands.html

Bringing this issue up because continuously doing `C-a` still alternates between first character and first non-whitespace character despite using `"emacs-mcx.strictEmacsMove": true`. With `M-m`, it can eliminate the use of this config.

**Comment by tuttieee** [comment]
> continuously doing `C-a` still alternates between first character and first non-whitespace character despite using `"emacs-mcx.strictEmacsMove": true`

That looks strange. Did you restart VSCode to make the change effective after setting the config?

**Comment by tuttieee** [comment]
Anyway, `M-m` will be added in the next release.
