### ISSUE TITLE
Yank Pop is not working in windows

### ISSUE THREAD

**Issue by starship863** [tuttieee/vscode-emacs-mcx#45]
Yank Pop is not working in windows. When invoke the "emacs-mcx.yank-pop", nothing happened.

No shortcut conflict for the command "emacs-mcx.yank-pop".

**Comment by ganaware** [comment]
M-y (yank-pop) works only after C-y (yank).
I'm using this extension on Windows7, and M-y works right.

On Emacs, M-y shows a message "Previous command was not a yank" to instruct its usage.

**Comment by tuttieee** [comment]
Thank you for reporting, @starship863 , and Thank you for your support, @ganaware !

I haven't checked the issue on Windows, however, at least, I will add the same instruction message as Emacs shows that may be helpful to see yank and yank-pop behavior.
