### ISSUE TITLE
Add message to yank-pop

### ISSUE THREAD

**Issue by tuttieee** [tuttieee/vscode-emacs-mcx#48]
"Previous command was not a yank" should be shown when yank-pop is invoked not after yank

**Comment by ganaware** [comment]
Once it is shown, the message "Previous command was not a yank" occupies the status bar for a long time. When will it disappear?

vscode.window.showInformationMessage() may be more appropriate than vscode.window.setStatusBarMessage() to show it.

**Comment by tuttieee** [comment]
Thank you, it is exactly right that the status bar message staying visible is annoying.
O
