### ISSUE TITLE
Command palette: Ctrl act like the 'Enter'

### ISSUE THREAD

**Issue by qqldd** [tuttieee/vscode-emacs-mcx#484]
I can reproduce with my windows and mac machine. When I hit ctrl, it act like 'Enter'. It will commit the highlighted command.

If I disable this extension. I don't see same behavior. This is annoying when I use ctrl-n/p to navigate then accidentally release it.

**Comment by tuttieee** [comment]
mm, that's strange. A single `ctrl` key is not assigned to any command with this extension, and I cannot reprodule it.

Please tell me the details of your environment.
For example, if you are using VSCode on macOS, you can see the summary from the menu item "Code" -> "About Visual Studio Code" then find something below
```
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:00:00.397Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

And please check if a single `ctrl` key is assigned to any key.
[The official document](https://code.visualstudio.com/docs/getstarted/keybindings) may be helpful.

**Comment by tuttieee** [comment]
Sorry, I found a problem and will fix it in the next release.

**Comment by qqldd** [comment]
Thanks! I got the fix and it is now okay!
