### ISSUE TITLE
Escape key cannot close parameter hints

### ISSUE THREAD

**Issue by ganaware** [tuttieee/vscode-emacs-mcx#49]
Escape key cannot close parameter hints.

"Parameter hints" is this popup list:
![2019-01-14 1](https://user-images.githubusercontent.com/9438/51115711-62761e00-184c-11e9-9cf4-1bbb95d9a465.png)

I think the following settings in the package.json:

```javascript
{
	"key": "escape",
	"command": "emacs-mcx.cancel",
	"when": "editorTextFocus"
},
```

override VSCode default settings:

```javascript
{ "key": "escape",                "command": "closeParameterHints",
                                     "when": "editorTextFocus && parameterHintsVisible" },
{ "key": "escape",                "command": "leaveSnippet",
                                     "when": "editorTextFocus && inSnippetMode" },
```

**Comment by tuttieee** [comment]
Thank you for reporting!
This will be fixed in the next release.
Sorry for inconvenience.
