### ISSUE TITLE
strictEmacsMove not working

### ISSUE THREAD

**Issue by yas99en** [tuttieee/vscode-emacs-mcx#539]
I installed Awesome Emacs keymap 0.23.5 to vscode 1.50.1.
I checked "Strict Emacs Move", but the cursor bahavior was not changed for Ctrl-a.

**Comment by tuttieee** [comment]
Have you reloaded VSCode?

**Comment by yas99en** [comment]
I'm sorry. The problem was solved by reloading vscode.
I'm a deep emacs user, but a beginner for vscode.
The behavior of 'move-beginning-of-line' is very important for me.

Thanks.
