### ISSUE TITLE
Please publish on Open VSX

### ISSUE THREAD

**Issue by jeannekamikaze** [tuttieee/vscode-emacs-mcx#578]
Hello,

This is to kindly request that the extension be published on [Open VSX](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) so that it is available on vscodium (free/libre version of vscode). If anyone has experience with this, any help in this regard would be appreciated to make the extension available to more people.

Thank you.

**Comment by tuttieee** [comment]
I published the extension on OpenVSX, though the namespace is and the extension is marked as unverified yet.
I'm claiming the ownership of the namespace now and it will be marked as verified after it is accepted.
https://open-vsx.org/extension/tuttieee/emacs-mcx

**Comment by jeannekamikaze** [comment]
Thanks Yuichiro, much appreciated. The editor is almost useless without this extension :)
