### ISSUE TITLE
Don't respect Lisp comments on forwardSexp and backwardSexp when we are editing non-Lisp documents

### ISSUE THREAD

**Issue by ganaware** [tuttieee/vscode-emacs-mcx#80]
The current implementations of forwardSexp and backwardSexp seem to be always respecting Lisp comments: ';'.

For example,  C# code is here:

```csharp
bool Foo { get { return bar != default(Baz); } }
```

When a forwardSexp is executed on the second '{', it should move the cursor to the next to the first '}'.
But it moves the cursor to the end of the document.
This is beacuse it respects the lisp comment ';' before the first '}'.

So, please don't respect Lisp comments when we are editing non-Lisp documents.

**Comment by tuttieee** [comment]
Now that behavior derived from paredit.js' code: https://github.com/rksm/paredit.js/blob/07f39ce097004beb49386ec7b41839a87af165b5/lib/reader.js#L58

To modify it,
1. fork paredit.js and fix it to be able to ignore comments
2. implement the original sexp parser

For now, I'm going to choose 1.

**Comment by tuttieee** [comment]
Another simple solution: to replace ";" with anther character

**Comment by ganaware** [comment]
Thank you but this problem is not fixed.

For example, C# code is here:

```csharp
bool Foo { get { return (foo); } }
bool Bar { get { return (bar); } }
bool Baz { get { return (baz); } }
```

- OK: When forwardSexp-ing on just after "Foo", the cursor moves to the end of the 1st line.
- NG: When forwardSexp-ing on just after "Bar", the cursor moves to the end of the document.
- NG: When forwardSexp-ing on just after "Baz", the cursor moves to the end of the document.

Hmm... only the first ';' is ignored?

**Comment by tuttieee** [comment]
Sorry, I found a bug and will fix it.

**Comment by ganaware** [comment]
It works good.  Thank you.
